export const ADD_TO_WANT_FROM_SEARCH = "ADD_TO_WANT_FROM_SEARCH";
export const USER_RATING = "USER_RATING";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const USER_RATING_FROM_SEARCH = "USER_RATING_FROM_SEARCH";
